### ISSUE TITLE
Is it possible to restrict to a certain version of pnpm?

### ISSUE THREAD

**Issue by Jinjiang** [pnpm/only-allow#12]
The background is I have a repo that requires `pnpm patch` however, it's a new feature of pnpm v7.4.0+ https://pnpm.io/cli/patch

It would be great if `only-allow` could also detect and allow a certain package manager version.

Thanks.

**Comment by zkochan** [comment]
Just use the engines field in package.json

https://pnpm.io/package_json#engines
