### ISSUE TITLE
Achieve without NPX

### ISSUE THREAD

**Issue by vhscom** [pnpm/only-allow#9]
Is there a way to achieve this without running NPX? Maybe https://www.npmjs.com/package/@antfu/ni has some ideas on doing it. I'm just not comfortable relying on NPX all the time as I consider it a security threat.

**Comment by jcollum-nutrien** [comment]
you can restrict npx to run only a specific version of a tool, that should alleviate any security threats

**Comment by vhscom** [comment]
The idea here was how to eliminate npx, not learn how to use its features. I suppose each of the tools supported are using some kind of lockfile. Keeping an internal list of lockfile names and keying off of those seems like the best approach to me. 

Here's what I would expect the api to look like when the changes are finished:

```json
"preinstall": "only-allow pnpm"
```

**Comment by arthurdenner** [comment]
> Here's what I would expect the api to look like when the changes are finished:
> 
> ```json
> "preinstall": "only-allow pnpm"
> ```

@vhscom, I think that's achievable if you install `only-allow` itself to your project, then the command becomes available without `npx`.

**Comment by vhscom** [comment]
It most certainly would. I think we can call this closed then. Sorry for my misunderstanding.
